# Generated by Django 4.2.8 on 2025-04-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inspecciones', '0001_initial'),
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspeccion',
            name='inspector',
            field=models.ForeignKey(limit_choices_to={'rol': 'trabajo_social'}, on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspeccion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='solicitudes.solicitud'),
        ),
    ]
